<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>K-Envoy</AssemblyName>
    <RootNamespace>K_Envoy</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="10.0.3" />
  </ItemGroup>

</Project>